controller_list:
  - name: fake_pointer_controller
    type: $(arg fake_execution_type)
    joints:
      - pointer_extend_joint
  - name: fake_body_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
initial:  # Define initial robot poses per group
  - group: body
    pose: home